---

#- name: Add the OS specific varibles
#  include_vars: "{{ ansible_os_family }}.yml"

- name: Install the openldap and required Packages for RedHat
  yum: name={{ item }} state=installed
  with_items: "{{ openldap_server_pkgs }}"
  when: ansible_os_family == 'RedHat'
  tags: pkginstall

- name: Enable slapd service
  systemd:
    name: slapd
    state: started
    enabled: True

- name: create the configuration directory
  file: path={{ openldap_server_app_path }}/slapd.d state=directory owner={{ openldap_server_user }} group={{ openldap_server_user }} mode=0750
  tags: config

- name: Generate the root password for ldap
  shell: slappasswd -s "{{ openldap_server_rootpw }}"
  register: root_password
  tags: config

- name: create the configuration directory
  file: path={{ openldap_server_app_path }}/files state=directory owner={{ openldap_server_user }} group={{ openldap_server_user }} mode=0755

- name: Copy files to /etc/openldap directory
  template: 
    src: "{{ item }}"
    dest: "{{ openldap_server_app_path }}/files"
    owner: "{{ openldap_server_user }}"
    group: "{{ openldap_server_user }}"
    mode: 0755
  with_items:
    - base-ldif.j2
    - certs-ldif.j2
    - db-ldif.j2
    - domain.ldif
    - monitor-ldif.j2
    - user-ldif.j2

- name: modify based DB db.ldif file
  shell: ldapmodify -Y EXTERNAL  -H ldapi:/// -f {{ openldap_server_app_path }}/files/db-ldif.j2

- name: modify monitor ldif  file
  shell: ldapmodify -Y EXTERNAL  -H ldapi:/// -f {{ openldap_server_app_path }}/files/monitor-ldif.j2

