---
- name: print varible
  debug:
    msg: "Domain name {{ openldap_server_domain_name }} and {{ openldap_server_pkgs }} "
  tags: vartest

- import_tasks: install_ldap.yml
- import_tasks: configure_ldap.yml
